float PS5ButtonX, PS5ButtonY, PS5ButtonWidth, PS5ButtonHeight;
float XSXButtonX, XSXButtonY, XSXButtonWidth, XSXButtonHeight;
float AppleButtonX, AppleButtonY, AppleButtonWidth, AppleButtonHeight;
float AndroidButtonX, AndroidButtonY, AndroidButtonWidth, AndroidButtonHeight;
float lightMouseButtonX, lightMouseButtonY, lightMouseButtonWidth, lightMouseButtonHeight;
float heavyMouseButtonX, heavyMouseButtonY, heavyMouseButtonWidth, heavyMouseButtonHeight;
float AMDButtonX, AMDButtonY, AMDButtonWidth, AMDButtonHeight;
float NvidiaButtonX, NvidiaButtonY, NvidiaButtonWidth, NvidiaButtonHeight;
float twelveHourTimeButtonX, twelveHourTimeButtonY, twelveHourTimeButtonWidth, twelveHourTimeButtonHeight;
float twentyFourHourTimeButtonX, twentyFourHourTimeButtonY, twentyFourHourTimeButtonWidth, twentyFourHourTimeButtonHeight;
float CocaColaButtonX, CocaColaButtonY, CocaColaButtonWidth, CocaColaButtonHeight;
float PepsiButtonX, PepsiButtonY, PepsiButtonWidth, PepsiButtonHeight;
float soccerButtonX, soccerButtonY, soccerButtonWidth, soccerButtonHeight;
float footballButtonX, footballButtonY, footballButtonWidth, footballButtonHeight;
float sixteenByTenButtonX, sixteenByTenButtonY, sixteenByTenButtonWidth, sixteenByTenButtonHeight;
float eightByFiveButtonX, eightByFiveButtonY, eightByFiveButtonWidth, eightByFiveButtonHeight;
float NikeButtonX, NikeButtonY, NikeButtonWidth, NikeButtonHeight;
float AdidasButtonX, AdidasButtonY, AdidasButtonWidth, AdidasButtonHeight;
Boolean PS5Correct=false, XSXIncorrect=false;
Boolean AppleCorrect=false, AndroidIncorrect=false;
Boolean lightMouseIncorrect=false, heavyMouseCorrect=false;
Boolean AMDCorrect=false, NvidiaIncorrect=false;
Boolean twelveHourTimeIncorrect=false, twentyFourHourTimeCorrect=false;
Boolean CocaColaCorrect=false, PepsiIncorrect=false;
Boolean soccerIncorrect=false, footballCorrect=false;
Boolean sixteenByTenIncorrect=false, eightByFiveCorrect=false;
Boolean NikeIncorrect=false, AdidasCorrect=false;
color PS5ButtonColour, XSXButtonColour;
color AppleButtonColour, AndroidButtonColour;
color lightMouseButtonColour, heavyMouseButtonColour;
color AMDButtonColour, NvidiaButtonColour;
color twelveHourTimeButtonColour, twentyFourHourTimeButtonColour;
color CocaColaButtonColour, PepsiButtonColour;
color soccerButtonColour, footballButtonColour;
color sixteenByTenButtonColour, eightByFiveButtonColour;
color NikeButtonColour, AdidasButtonColour;
color choosingButtonColourInverted;
